#We are going to assume that a line is equal to 20 steps, this means 5 lines is 100 steps
#Where the turtle starts might depend on the size of your screen since we have different sized screens
#Wherever it starts that's where the top of the screen is
import turtle
import random

from turtle import Turtle
#This function is just to add some random colors to our turtle
def randomColor():
    colors = ["RED","ORANGE","GREEN","BLUE"]
    randomNum = random.randrange(0,4)
    return colors[randomNum]
def draw3(banner):
    banner.forward(12)
    banner.down()
    banner.backward(20)
    banner.forward(20)
    banner.setheading(0) 
    banner.circle(25,180)
    banner.forward(20)
    banner.backward(20)
    banner.setheading(0) 
    banner.circle(25,180)
    banner.forward(20)   
def draw7(banner):
    banner.forward(20)
    banner.down()
    banner.forward(50)
    banner.setheading(265)
    banner.forward(100)
    banner.setheading(0)
    banner.up()
    banner.forward(70)

def drawI(banner):
    banner.down()
    banner.forward(50)
    banner.backward(25)
    banner.setheading(90)
    banner.forward(100)
    banner.setheading(0)
    banner.forward(25)
    banner.backward(50)
    banner.up()
    banner.forward(70)
    
def drawS(banner):
    banner.down()
    banner.forward(50)
    banner.left(90)
    banner.forward(50)
    banner.left(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.up()
    banner.forward(30)
    banner.setheading(270)
    banner.forward(100)
    banner.setheading(0)
def drawC(banner):
    banner.setheading(180)
    banner.down()
    banner.backward(50)
    banner.forward(50)
    banner.left(90)
    banner.forward(100)
    banner.left(90)
    banner.forward(50)
    banner.up()
    banner.forward(30)
def draw8(banner):
    banner.down()
    banner.forward(100)
    banner.right(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.backward(50)
    banner.left(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.up()
    banner.right(189)
def draw4(banner):
    banner.down()
    banner.forward(50)
    banner.right(90)
    banner.forward(18) 
    banner.backward(50)
    banner.left(60)
    banner.forward(65)
    banner.right(150)
    banner.forward(58)
    banner.up()
    banner.forward(50)
    banner.left(90)
def draw9(banner):
    banner.pencolor(randomColor())
    banner.down()
    banner.forward(45)
    banner.left(90)
    banner.forward(105)
    banner.left(90)
    banner.forward(45)
    banner.left(90)
    banner.forward(45)
    banner.left(90)
    banner.forward(45)
    banner.right(90)
    banner.forward(60)
    banner.left(90)
    banner.up()
def draw1(banner):
    banner.pencolor(randomColor())
    banner.left(90)
    banner.forward(90)
    banner.right(45)
    banner.down()
    banner.forward(30)
    banner.right(135)
    banner.forward(115)
    banner.left(90)
    banner.backward(30)
    banner.forward(60)
    banner.up()
def draw2(banner):
    banner.down()
    banner.forward(50)
    banner.right(90)  
    banner.forward(50)
    banner.right(90)  
    banner.forward(50)
    banner.left(90)  
    banner.forward(50)
    banner.left(90)  
    banner.forward(50)
    banner.up()
def drawE(banner):
    banner.down()
    banner.forward(50)
    banner.backward(50)
    banner.left(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.backward(50)
    banner.left(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.backward(50)
    banner.right(90)
    banner.up()
    banner.forward(105)
    banner.left(90)
def drawLine(banner,line):
    line *= 20
    banner.right(90)
    banner.forward(line)
    banner.left(90)    
def drawN(banner):
    banner.down()
    banner.left(90)
    banner.forward(100)
    banner.right(160)
    banner.forward(110)
    banner.left(160)
    banner.forward(110)
    banner.backward(110)
    banner.right(90)
    banner.up()
    banner.forward(30)
def drawT(banner):
    banner.pencolor(randomColor())
    banner.down()
    banner.forward(50)
    banner.backward(25)
    banner.right(90)
    banner.forward(100)
    banner.right(90)
    
def drawA(banner):
    banner.left(40)
    banner.up()
    banner.forward(20)
    banner.left(80)
    banner.down()
    banner.forward(50)
    banner.right(80)
    banner.forward(20)
    banner.backward(20)
    banner.left(80)     
    banner.forward(50)
    banner.right(80)
    banner.right(80)
    banner.forward(105)
    banner.left(80)
    
def drawR(banner):
    banner.down()
    banner.right(90)
    banner.forward(100)
    banner.right(90)
    banner.forward(60)
    banner.right(140)
    banner.forward(80)
    banner.left(100)
    banner.forward(80)
def drawCircle(Banner):
    banner.pencolor(randomColor())
    banner.down()
    banner.circle(50,360)
    banner.up()
    banner.backward(50)
    banner.left(90)
    

def drawF(banner):
    banner.pencolor(randomColor())
    banner.down()
    banner.right(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.backward(50)
    banner.left(90)
    banner.forward(50)
    banner.right(90)
    banner.forward(50)
    banner.backward(50)
    banner.right(90)
    banner.forward(50)
    banner.left(90)
    banner.up()
    banner.forward(160)
    banner.left(90)
def moveToLeftTop(banner):
    banner.left(90)
    banner.left(90)
    banner.up()
    banner.forward(678)
    banner.left(270)
    banner.forward(350)
    banner.right(90)


banner = Turtle()
screen = turtle.Screen()
screen.setup(width = 1.0, height = 1.0)
moveToLeftTop(banner)
lines = 5
drawLine(banner, lines)
drawT(banner)


banner.up()
banner.backward(20)
banner.down()
banner.pensize(5)
banner.backward(3)
banner.up()
banner.backward(20)

banner.pensize(1)
drawF(banner)
drawCircle(banner)
banner.backward(20)
drawF(banner)
drawCircle(banner)
banner.backward(20)
drawR(banner)
drawA(banner)
banner.up()
banner.forward(30)
drawN(banner)
drawE(banner)
lines = 2
drawLine(banner,lines)
y = banner.ycor()
banner.goto(-350,y)
draw2(banner)
banner.forward(80)
drawCircle(banner)
banner.up()
banner.right(90)
banner.forward(125)
draw1(banner)
banner.forward(25)
draw9(banner)
banner.forward(80)
drawCircle(banner)
banner.right(90)
banner.forward(150)
banner.left(90)
draw4(banner)
banner.forward(50)
draw9(banner)
banner.forward(30)
draw1(banner)
banner.forward(20)
banner.left(90)
draw8(banner)
lines = 2
drawLine(banner,lines)
y = banner.ycor()
banner.goto(-350,y)
drawC(banner)
drawS(banner)
drawI(banner)
drawT(banner)
banner.up()
banner.setheading(0)
banner.forward(30)
banner.setheading(90)
banner.forward(100)
banner.setheading(0)
draw7(banner)
drawCircle(banner)
banner.setheading(0)
banner.forward(125)
draw3(banner)

turtle.done()